# pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3      # Banco de dados NoSQL leve
  hive_flutter: ^1.1.0 # Integração do Hive com o Flutter
  path_provider: ^2.0.11 # Ajuda a encontrar o caminho para o BD

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0 # Para gerar o código de adaptação do modelo
  build_runner: ^2.1.11  # Ferramenta para executar o gerador de código